# Generated by Django 5.2.6 on 2025-09-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='user_images/user.png', upload_to='user_images', verbose_name='Фото пользователя'),
        ),
    ]
